### ISSUE TITLE
Validate checkout repository references

### ISSUE THREAD

**Issue by ModernRonin** [sharpliner/sharpliner#164]
Say, you do something like:

```csharp
 new RepositoryCheckoutTask("Cloud") { FetchDepth = 1 }
```

without having defined the repository under resources.

currently, it will compile without error only when trying to run the pipeline on Devops, you'll get a message
> Checkout of repository 'Cloud' is not supported. Only 'self', 'none', or a repository alias are supported.

It would be nice (and I think in the spirit of Sharpliner) if this could be caught at compile time.

Cheers,
Markus / MR

**Comment by premun** [comment]
Makes sense! Should be easy to add.

Thanks for the idea! I'll see when I get to it or feel free to take it too.

**Comment by ModernRonin** [comment]
a related question: I noticed all pipelines have `.Validate()` methods - are these called automatically on build? or am I supposed to call them myself from a unit-test?

I don't know how much chance I will have to do any PRs this weekend - because this weekend is all the time I have to split a fairly complicated release pipeline into multiple ones to bring down the time the actual release step takes. 
However, for the same reason this weekend you'll probably see me creating more issues here and, whenever I feel that makes sense, I'll also just add a few code-snippets from my usage. 

My thinking is that by doing so:
*) better than nothing
*) you can check them out and decide whether this is something you want to include in Sharpliner or not
*) they might give other users ideas
*) later -probably next weekend- when I don't have stress with the bread-job on the weekend, I can come back to those you find worthy and make them properly pretty

**Comment by premun** [comment]
Cool, whatever works for you works for me!

To your question: yes these are called automatically. In the build output, you should see a line saying something like "Validating pipeline..."
