### ISSUE TITLE
Ability to consume pipelines from other assemblies

### ISSUE THREAD

**Issue by jshield** [sharpliner/sharpliner#175]
Hey guys, really awesome library you have here.

So here is the scenario:

I'd like to be able to publish a set of baseline pipelines that can be consumed through traditional packaging methods such as a nuget package such that a downstream team can extend from an abstract class filling in certain properties and getting a fully rendered pipeline out as a result.

so far a couple of things I have noticed, 
1. the msbuild task fires by default, was able to disable the behaviour by excluding build assets in the baseline library reference to Sharpliner
2. and the real killer, seems that the msbuild task has issues resolving assemblies references that aren't YamlDotNet and Sharpliner.

``` csharp

// Baseline.Templates assembly

namespace Baseline.Templates;

public abstract class PublishToolsPipeline : SingleStagePipelineDefinition
{

    public abstract string MajorMinor { get; }
    
    public abstract string Project { get;  }

    public override string TargetFile => GetType().GetTargetFileFromAttribute<PipelineOutput>();

    public override SingleStagePipeline Pipeline => new()
    {
        
        Variables =
        {
            Variable("majorMinor",MajorMinor),
            Variable("patch", "$[counter(variables['majorMinor'], 0)]"),
            Variable("version" ,"$(majorMinor).$(patch)")
        },
        Jobs =
        {
            new Job("Publish", "Publish to AWE DevOps")
            {
                Pool = HostedPools.Ubuntu,
                Steps =
                {
                    Tasks.NugetAuthenticate("Authenticating Against Azure Artifact Feeds"),
                    DotNet.Install.Sdk("6.x"),
                    DotNet.Restore.FromNuGetConfig("Nuget.config") with
                    {
                        DisplayName = "Restoring Feeds in Nuget.config",
                    },
                    DotNet.Pack(Project) with
                    {
                        DisplayName  = "Packaging Azure DevOps Pipeline Tools",
                        ConfigurationToPack = "Release",
                        Arguments = "/p:PackageVersion=$(version)"

                    },
                    If.And(IsNotPullRequest, IsBranch("master"))
                        .Step(Tasks.PushToDevOps("Publish to DevOps Feed","$(Build.SourcesDirectory)/**/*.nupkg;!$(Build.SourcesDirectory)/**/*.symbols.nupkg"))
                }
            }
        }
        
    };
}

public static class HostedPools
{
    public static readonly HostedPool Ubuntu = new HostedPool("Azure Pipelines", "ubuntu-latest");
}

public static class Tasks
{
    public static AzureDevOpsTask NugetAuthenticate(string displayName) => new("NuGetAuthenticate@0") {DisplayName = displayName};

    public static AzureDevOpsTask PushToDevOps(string displayName, string packages = "") => new("NuGetCommand@2")
    {
        DisplayName = displayName,
        Inputs = new()
        {

            {"command", "push"},
            {"packagesToPush", packages},
            {"nuGetFeedType", "internal"},
            {"publishVstsFeed", "<redacted to protect the innocent>"},
        }
    };
}

```

``` csharp

// AzDo.Pipeline.Lint.Pipelines assembly.

namespace AzDo.Pipeline.Lint.Pipelines;

[PipelineOutput("../azure-pipelines.yml")]
public class PublishAzDoPipelineLintPipeline : PublishToolsPipeline
{
    public override string MajorMinor => "1.0";
    public override string Project => "azdo-pipeline-lint.sln";
}

```

```
  dotnet build --project AzDo.Pipeline.Lint.Pipelines -c Release
 
  Sharpliner.targets(20, 5): [MSB4018] The "PublishDefinitions" task failed unexpectedly.
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load file or assembly 'Baseline.Templates, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. General Exception (0x80131500)
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Sharpliner.PublishDefinitions.FindAllImplementations[T](Boolean isInterface)
   at Sharpliner.PublishDefinitions.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)
System.IO.FileLoadException: Could not load file or assembly 'Baseline.Templates, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. General Exception (0x80131500)
File name: 'Baseline.Templates, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
 ---> System.Exception: Failed to find Sharpliner dependency Baseline.Templates, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
   at Sharpliner.PublishDefinitions.<>c__DisplayClass12_0.<LoadAssembly>g__ResolveAssembly|4(Object sender, ResolveEventArgs e)
   at System.Runtime.Loader.AssemblyLoadContext.InvokeResolveEvent(ResolveEventHandler eventHandler, RuntimeAssembly assembly, String name)
   at System.Runtime.Loader.AssemblyLoadContext.OnAssemblyResolve(RuntimeAssembly assembly, String assemblyFullName)
```

am I doing something wrong?

**Comment by jshield** [comment]
Changing the entry to LoadAssembly in PublishDefinitions to:
``` csharp
    /// <summary>
    /// Loads the assembly and all of its dependencies (such as YamlDotNet).
    /// </summary>
    private Assembly LoadAssembly(string assemblyPath)
    {
        var fullAssemblyPath = Path.GetFullPath(assemblyPath);
        var assemblyDirectory = new DirectoryInfo(Path.GetDirectoryName(fullAssemblyPath));

        // Preload dependencies needed for things to work
        var  assemblies = assemblyDirectory.GetFiles("*.dll")
```

works well enough, maybe allow passing in a filter to exclude/include additional assemblies in addition to the existing YamlDotNet/Sharpliner deps?

**Comment by premun** [comment]
Hi @jshield,

Thanks for the feedback. This sounds like a very reasonable scenario/ask and I would like to support this scenario well with Sharpliner. However, we can now work together to get you unblocked asap and a proper solution can come later.

1. What happens if you keep all your classes in the baseline library abstract? The MSBuild target will fire but nothing should get generated, right?

2. This part of Sharpliner I am still not very happy with. I am not able to load the types into the main domain still, so I cannot even cast classes and call interfaces directly. I believe if I solved that part everything might start working from there. I found a clue in an MSBuild tech talk so I might be on a good track. Meanwhile, what you propose should work - passing a list of filenames should do the trick. Would you prefer setting MSBuild properties or some static C# field?

**Comment by jshield** [comment]
Hey @premun, thanks for the quick response.

1. is not particularly an issue, was more just an observation, and I get a bit than anything else about unnecessary build activities, we may end up porting the existing YAML based framework we have to C# so having those being generated from the common library may be a feature.

2.  From a purely dev focus, I'd imagine being able to declare a static class with a property containing a list of names of assemblies to load and other global configuration would be an ideal starting place,
``` csharp

public static class SharpLinerConfiguration {

  public static readonly string[] Assemblies = {"Baseline.Templates.dll", "Other.Assembly.dll"};

}

```

however if it is easier to load the configuration in MSBuild, then a set of MSBuild properties would be fine as well. 

Would also allow for being set at the root of the repo via Directory.Build.props,

Something similar to 
``` xml
<ItemGroup>
  <SharpLinerAssemblies Include="Baseline.Templates.*.dll" Exclude="Baseline.Templates.Legacy.dll"/>
</ItemGroup>
```
or as a PropertyGroup 
``` xml
<PropertyGroup>
  <SharpLinerAssembliesInclude>Baseline.Templates.*.dll</SharpLinerAssembliesInclude> 
  <SharpLinerAssembliesExclude>Baseline.Templates.Legacy.dll</SharpLinerAssembliesExclude>
</PropertyGroup>
```

**Comment by premun** [comment]
I am going to have to set your scenario up to try out both options.

I think `ItemGroup` might make a lot of sense as it is a native solution and offers things such as matching files like your example. However, the files have to be present there first so it has to happen in the right time and with the right paths.

C# settings might prove more complicated because we don't have access to the right paths.

**Comment by premun** [comment]
@jshield what you proposed works well even without having to supply the list of assemblies - just load everything.

I published a new version 1.2.8 that should get you going - https://www.nuget.org/packages/Sharpliner/1.2.8

**Comment by jshield** [comment]
@premun Thanks a lot mate this works perfectly for my plan.

**Comment by premun** [comment]
@jshield let me know if you make this work (or close the issue directly).

FYI I have added E2E tests testing this scenario so that future versions won't break it (#180).

**Comment by jshield** [comment]
Yep, was able to replace my local build with 1.2.8 and it worked without issue. So i'm happy to close the issue. Once again thanks!
