### ISSUE TITLE
Pipeline parameters are missing

### ISSUE THREAD

**Issue by premun** [sharpliner/sharpliner#208]
Coming from: https://github.com/sharpliner/sharpliner/discussions/207

### Problem

It should be possible to define parameters to pipelines as described here:
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/runtime-parameters?view=azure-devops&tabs=script

It seems that the possible types are the same as with template parameters so this should be fairly easy to implement.

### Goals

- Create the `Parameters` field (no conditionals) on `Pipeline`
- Make it possible to use shorthands from `TemplateDefinition` insde `PipelineDefinition`
- Make it possible to reference parameters like in templates
- Extend documentation

**Comment by brunskutscher** [comment]
i think it's not that easy.
the problem is, that a a pipeline parameter has an additional property (i.e.  "displayName").
this is the real advantage of parameters on pipeline level.  they will be shown/editable/selectable in the run ui of portal.
it doesnt fit in the model so far. 
we can copy the whole template parameter stuff to have a pipeline parameter with one additional property.
buts this is ugly.

**Comment by premun** [comment]
I see. Is there a way we could somehow use generics and have a `TemplateParameter` and `PipelineParameter` inherit and add this?
The methods for creating these could then probably carry this type information and return whatever is needed?

It would probably be fine having 2 sets of APIs too and in the pipeline version have the `displayName` parameter as an argument because we frequently surface this one in the other APIs.

**Comment by premun** [comment]
@brunskutscher I checked the code and I think I see a way how to implement this nicely.

1. Make ctors of `TemplateParameter` classes **internal**
2. Add parameter to the ctor for `displayName`, add the same property
3. Keep the methods for parameter creation in `TemplateDefinition` without display name
4. Copy the methods for parameter creation from `TemplateDefinition` into `PipelineDefinition` and add the `displayName` parameter so that you force people to set it in pipeline

This way, we don't need to copy much of the code. Only regression is that you won't be able to `new` the parameters but I don't think people do that anyway.

Are you still interested in this?

**Comment by premun** [comment]
So it was actually super quick to implement and the change was quite small so I added this as it is a missing feature that might be desired by customers:
https://github.com/sharpliner/sharpliner/pull/210

However, I am happy to help find something else if you're interested in contributing!

**Comment by premun** [comment]
Ah, thanks for the feedback!

Yeah, I agree renaming makes sense and making display name optional too. I should have left the PR up for some time to give you time to review. Sorry about that.

Can you open a PR for this? Or should I make the change?

**Comment by brunskutscher** [comment]
no problem ... 
coincidental i worked on this today.
but i have limited time ... so better you make the change and i will review it as soon as possible.

**Comment by premun** [comment]
Fixed in #210 and #211
