### ISSUE TITLE
nuGetConfigPath and requiring feedsToUse

### ISSUE THREAD

**Issue by thomhurst** [sharpliner/sharpliner#214]
Hi - I have a project with a custom `nuget.config` file.
I set a dotnet restore task like this:
```csharp
                    DotNet.Restore.Projects("**/AcceptanceTests.csproj") with
                    {
                        NuGetConfigPath = "src/nuget.config",
                        DisplayName = "Restore Acceptance Test Packages"
                    },
```

For me, that failed, and I can see in my yaml from before I used to have a `"feedsToUse": "config"`

FeedsToUse wasn't available, but I was able to manually add it via the Inputs section.

```csharp
                    DotNet.Restore.Projects("**/AcceptanceTests.csproj") with
                    {
                        Inputs = new TaskInputs
                        {
                            { "feedsToUse", "config" }
                        },
                        NuGetConfigPath = "src/nuget.config",
                        DisplayName = "Restore Acceptance Test Packages"
                    },
```

Maybe have FeedsToUse to be a settable property, or if nugetConfigPath is set, always set that value to "config" ?

Thanks

**Comment by premun** [comment]
Hey,

Please have a look at `DotNet.Restore.FromNuGetConfig()`. Does it work better?

But I will keep this open and make the setter of `NuGetConfigPath` set the `feedsToUse`.

**Comment by premun** [comment]
@thomhurst I made a change which will set `feedsToUse` automatically when `nugetConfigPath` is specified: #216
