### ISSUE TITLE
Version 42.42.42 in NuGet

### ISSUE THREAD

**Issue by thomhurst** [sharpliner/sharpliner#222]
I assume this was an error or beta version as it doesn't follow the other versions.

You might want to unlist this package as it is shown as the highest current available version.

**Comment by premun** [comment]
This must be a mistake. 42.42.42 was uploaded a long time ago and unlisted right away. I see it unlisted even now in the nuget.org portal and the portal says 1.3.6 is the newest.

Can you share where were you given this version?

**Comment by thomhurst** [comment]
I use Rider as my IDE and it shows it in the Rider Nuget UI

**Comment by premun** [comment]
That sounds like a bug in Rider then?

**Comment by thomhurst** [comment]
Hmm yeah maybe you're right. I've checked the nuget site and can't see it. I'll close this, apologies!

**Comment by premun** [comment]
No worries!
