### ISSUE TITLE
Parameters are using Compile-Time Expressions in Conditions but should be using Runtime Expressions

### ISSUE THREAD

**Issue by thomhurst** [sharpliner/sharpliner#230]
Take this C# code:

```csharp
If.Equal(parameters["restore"], "true")
```

This produces the following YAML:

```yaml
 ${{ if eq('${{ parameters.restore }}', 'true') }}:
```

This is incorrect.
A valid syntax would be:

```yaml
 ${{ if eq(parameters['restore'], 'true') }}:
```

**Comment by premun** [comment]
Also sort of related to this: https://github.com/sharpliner/sharpliner/issues/125

**Comment by premun** [comment]
I see the problem. This is not about runtime/compile time as the syntax should not matter (based on https://docs.microsoft.com/en-us/azure/devops/pipelines/process/runtime-parameters).

I think the problem is having `${{` inside of another one

**Comment by premun** [comment]
@thomhurst can you please confirm that it works with `1.4.1`?

**Comment by thomhurst** [comment]
Yes that worked!
