### ISSUE TITLE
Variables don't serialize into Macro Expression syntax

### ISSUE THREAD

**Issue by thomhurst** [sharpliner/sharpliner#232]
Given this C#

```csharp
Script.Inline($"echo {variables["MyVariable"]}"),
```

The yaml produced is:

```yaml
  - script: |-
      echo variables['MyVariable']
```

This doesn't work. For variables to work in string/variable interpolation they need to use Macro expression syntax.

This would be:
```yaml
  - script: |-
      echo $(MyVariable)
```

**Comment by thomhurst** [comment]
#233

**Comment by premun** [comment]
I see some nullability problems on the main build after the merge. I will do one more sanity check in the evening before releasing a new version

**Comment by thomhurst** [comment]
Hope it's all good :)

**Comment by premun** [comment]
A new version is out! 1.4.2
