### ISSUE TITLE
Parameter Default Values are not used if they're value type defaults

### ISSUE THREAD

**Issue by thomhurst** [sharpliner/sharpliner#236]
I've tried declaring a BooleanParameter with a default value of false, but this doesn't serialise into the pipeline.

I then get an error when running the pipeline saying I must set a parameter value (since it has no default)

I suspect the same would be if you tried an integer with a value of 0.

**Comment by premun** [comment]
This is fixed in [`1.4.4`](https://github.com/sharpliner/sharpliner/releases/tag/1.4.4)
