### ISSUE TITLE
ObjectParameter but with List instead of Dictionary?

### ISSUE THREAD

**Issue by mathiasi** [sharpliner/sharpliner#259]
I'm testing out Sharpliner and trying to migrate our current pipeline.
We have one parameter as following:

```
- name: myName
  displayName: My List
  type: object
  default: ['value 1', 'value 2']
```
and I can't seem to replicate this in Sharpliner. As far as I can tell there is only one ObjectParameter and it only accepts a Dictionary.

I was trying to implement a `Parameter<ConditionedList<string>>` but the constructors of Parameter is internal. Would it be worth it to consider making it public? I might have been able make my own implementation by doing so.

**Comment by premun** [comment]
Support added in `1.4.9` - https://github.com/sharpliner/sharpliner/releases/tag/1.4.9

**Comment by premun** [comment]
Thanks again, @mathiasi
