### ISSUE TITLE
RepositoryResource doesn't serialize RepositoryType.Git

### ISSUE THREAD

**Issue by thomhurst** [sharpliner/sharpliner#272]
When I add a RepositoryResource to my Pipeline, with a RepositoryType of RepositoryType.Git, it doesn't serialize into the YAML.
My pipeline doesn't like this and errors with the following:

```
Value cannot be null. Parameter name: key
```

After re-adding the repository type into the YAML manually, the pipeline succeeds.

Can we make this serialize into the YAML?

**Comment by premun** [comment]
@thomhurst can you share your definition?

I tried following and it worked: https://github.com/sharpliner/sharpliner/blob/91c0f7fa7c8c4d3e829c6df93be596e5b3fd9931/tests/Sharpliner.Tests/AzureDevOps/Model/PipelineResourceSerializationTests.cs

**Comment by thomhurst** [comment]
How bizarre. I've tested my definition against that test and it produces the expected output.

Could the fact it's running during the compilation affect this in any way?

**Comment by premun** [comment]
It should be the same code path but there could be a difference in your definition in little things for instance when you're new-ing objects such as `new Resources()` where a plain `new()` would give you a `Conditioned` might invoke a different ctor. But if you literally copied your whole definition, the other thing I can think of are the pipeline validations which run only during the final compilation.

Can you give me the whole stack trace?

**Comment by thomhurst** [comment]
@premun I've created a reproduceable repo - Hope this helps?

https://github.com/thomhurst/Sharpliner.MissingRepositoryType.Reproducer/tree/main/Sharpliner.MissingRepositoryType.Reproducer

**Comment by premun** [comment]
@thomhurst I cloned your repo and tried building Debug and Release both from console and Visual Studio (on Windows). I also tried building in WSL for Linux x64.

I didn't get a repro. Can you check you're getting version 1.5.2 restored?

**Comment by thomhurst** [comment]
@premun Yep the assembly is loaded from a 1.5.2 nuget package.

<img width="503" alt="image" src="https://user-images.githubusercontent.com/30480171/230604269-66551578-6558-4d06-8c9e-d4c6b2ba07fc.png">

So if you build that repro project, does the YAML change with the RepositoryType added?

I've just tried on a different Windows 11 machine and it's still not adding the RepositoryType.

**Comment by premun** [comment]
Yeah, all seems to work just fine:

![image](https://user-images.githubusercontent.com/7013027/230777875-6640e738-b0ec-44fc-a58e-dadf77ee85ea.png)

**Comment by thomhurst** [comment]
So the issue I'm raising is that yaml file should also include:

```
type: git
```

**Comment by premun** [comment]
Oooh, apologies. I misunderstood from the beginning. I thought the exception happens in Sharpliner when serializing the YAML and not within Azure DevOps.

A fix for this should be very simple! https://github.com/sharpliner/sharpliner/pull/273
