### ISSUE TITLE
Extends definition

### ISSUE THREAD

**Issue by asos-neildownes** [sharpliner/sharpliner#283]
Hello, 

Are there any plans to add template extension capabilities, using the extends definition?

Documented here -> https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/extends?view=azure-pipelines

Thanks

**Comment by premun** [comment]
Hey,
Yeah, I've discovered this feature just recently and it should be possible to add. I need to read more to understand the full syntax.

Thanks for reporting the issue

**Comment by premun** [comment]
Looking into this now. Should be an easy add

**Comment by premun** [comment]
@asos-neildownes I added the support. You need to inherit from `ExtendsPipelineDefinition` in your code.

The change will be in the `1.5.8` version of the package in a couple of minutes.
