### ISSUE TITLE
Workspace = JobWorkspace.All result in error on DevOps Pipeline

### ISSUE THREAD

**Issue by MichielNL83** [sharpliner/sharpliner#309]
In my Pipeline Definition under a Job i define 
`Workspace = JobWorkspace.All `

In my yml filel this gets translated to:
`workspace: All`

with this added my pipeline in Azure DevOps fails.

If i look at the documentation from Microsoft:
https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/workspace?view=azure-pipelines

The correct output should be:

`workspace:
  clean: all
`

**Comment by premun** [comment]
Hi, thanks for reporting this. It should be an easy fix. I will have a look at it soon.

**Comment by premun** [comment]
@MichielNL83 you can bump Sharpliner to `1.5.16` which has the fix
