### ISSUE TITLE
How do I use runtime expressions?

### ISSUE THREAD

**Issue by ricardoboss** [sharpliner/sharpliner#311]
Hi! Great project, love using it!

I have a pipeline that determines which steps need to run based on variables set from previous steps.

Basically a "Has this file changed? If yes, do this step, if not, do the other step".

It's almost working, but the way the `If.Step` works is by emitting compile-time expressions, which is not very helpful if the variable I want to test is only available at runtime.

See also: https://learn.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#code-try-1

How can I use runtime expressions?

**Comment by premun** [comment]
Hey,
So I think this is not that well supported but still doable.
For instance, you can always set the `Condition` property on a job/step/stage like so:

```csharp
Jobs =
[
    new Job("job1")
    {
        Condition = Condition("$[" + IsBranch("main") + "]"),
    }
]
```

where the `Condition()` just accepts a string (any condition) while there are still some helper methods available.
But I think right now there is no method that would wrap stuff in `$[ ... ]`.

If you have an idea how to support this nicely, I am all open.

**Comment by ricardoboss** [comment]
Ah, I see. As it turns out, what I was trying to do doesn't even work anyways... Nonetheless, I have no expectation of how runtime expression should look like in Sharpliner. Feel free to close this issue, as you have answered my question after all :)

**Comment by premun** [comment]
Alright then
