### ISSUE TITLE
extension methods

### ISSUE THREAD

**Issue by erstert3st** [sharpliner/sharpliner#314]
I really like your project and I am interested in writting some extension methods for it.  I am thinking of creating extension Methods that call our templates with different arguments, similar to #150  , but with a bit more complexity, overloading and with some comments for clarity.

In order to do this, I would need the Template constructor to be public. Would it be possible for you to change the access modifier of the Template constructor from 'internal' to 'public'? Here's what the change would look like:
internal Template(string path, TemplateParameters? parameters = null) : this(null, path, parameters)
public Template(string path, TemplateParameters? parameters = null) : this(null, path, parameters)

**Comment by erstert3st** [comment]
#316 GH-316

**Comment by premun** [comment]
Hi, thanks for the change, this is perfectly reasonable!
Merged, will be in the next version (I believe 1.5.18)
