### ISSUE TITLE
Enum as a template parameter?

### ISSUE THREAD

**Issue by ManelRosPuig** [sharpliner/sharpliner#318]
Hi there! I'm really new to using this nuget so any help is appreciated. Please feel free to correct me on anything.

I find myself creating a template in which I have to use the Checkout repository. More specifically I want to parameterize the Submodules. But the problem is the Submodules parameter only accepts one of the Enumeration values, but I really want it to be passed as a parameter: ${{ parameters.submodules }}. I am trying something like:
```csharp
public override List<Parameter> Parameters => new()
{
    StringParameter("repository"),
    StringParameter("submodules", defaultValue: "true")
};

public override ConditionedList<Step> Definition => new()
{
    new RepositoryCheckoutTask(parameters["repository"])
    {
        Submodules = parameters["submodules"]
    }
};
```
But id does not work because it expects a value of type `Sharpliner.AzureDevOps.Tasks.SubmoduleCheckout`. Here is the full error:
```
Cannot implicitly convert type 'Sharpliner.AzureDevOps.ConditionedExpressions.ParameterReference' to 'Sharpliner.AzureDevOps.Tasks.SubmoduleCheckout'
```
Is there any solution to this? Thank you very much in advance! :)

**Comment by premun** [comment]
Hey,
Thanks for logging the issue!

I believe we can make it work but it will need a small change in Sharpliner. I can see if I can get a PR out. Should be quite straightforward.

**Comment by premun** [comment]
Alright, I have a fix: https://github.com/sharpliner/sharpliner/pull/319
It will appear in the `1.5.20` package which will be published shortly.

@ManelRosPuig please also note you can use a shorter notation for the checkout task:
```csharp
    Checkout.Repository(parameters["repository"]) with
    {
        Submodules = parameters["submodules"]
    }
```
