### ISSUE TITLE
Remove support for dotnet 7

### ISSUE THREAD

**Issue by Meir017** [sharpliner/sharpliner#338]
Dotnet 7 is no longer supported https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core

![image](https://github.com/user-attachments/assets/755aa57b-c8c3-41ad-88d9-2e2ecd23c098)

**Comment by premun** [comment]
While it won't be supported, I think many people still use this and it doesn't cost us much to multi-target the nupkg to 6/7/8/9 so I'd maybe keep it for now. It's not like the CVEs are of any concern really and people stuck on 7.0 can keep getting updates still
