### ISSUE TITLE
Remove support for dotnet 6

### ISSUE THREAD

**Issue by Meir017** [sharpliner/sharpliner#339]
Dotnet 6 will stop being supported on November 12th https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core

**Comment by premun** [comment]
While it won't be supported, I think many people still use this and it doesn't cost us much to multi-target the nupkg to 6/7/8/9 so I'd maybe keep it for now. It's not like the CVEs are of any concern really and people stuck on 6.0 can keep getting updates still
