### ISSUE TITLE
Allow referncing templates in a strongly-typed way

### ISSUE THREAD

**Issue by Meir017** [sharpliner/sharpliner#356]
Instead of using `TemplateParameters` it would be nice to have a strongly-typed parameters class.

currently:
```cs
.JobTemplate("template1.yml", new TemplateParameters
{
    { "enableTelemetry", true },
})
```

goal:
```cs
.JobTemplate<Template1>(new()
{
    EnableTelemetry = true
})
```

This achieves two things:
- Removing the explicit need to specify the template path
- Removing the explicit need for parameter names and dynamic types

**Comment by ManelRosPuig** [comment]
That would be amazing!👍👍

**Comment by premun** [comment]
I think the right solution to this would be adding source generators that would generate these APIs for you. I already did some experiments some time ago on this topic: 
https://github.com/sharpliner/sharpliner/issues/150

I think it's a difficult problem. It might be easier if we could just analyze a built assembly with user's definitions rather than getting it out of the AST in generators. But it's a workable problem

**Comment by Meir017** [comment]
@premun I think we could have a classes that convert a simple POCO into `TemplateParameters` & `List<Parameter>`

```cs
public interface ITemplateParametersProvider
{
    TemplateParameters ToTemplateParameters();
}
```

so for defining the template:

```cs
public abstract class JobTemplateDefinition<TParameters> : JobTemplateDefinition
    where TParameters : ITemplateParametersProvider, new()
{
    public sealed override List<Parameter> Parameters => GetParameters(TemplateParameters);

    [DisallowNull]
    public TParameters TemplateParameters { get; } = new TParameters();

    private static List<Parameter> GetParameters(TParameters parameters)
    {
        var result = new List<Parameter>();
        foreach (var parameter in typeof(TParameters).GetProperties()
            .Where(IsParameterProperty))
        {
            var paramType = parameter.GetType();
            if (paramType == typeof(string))
            {
                result.Add(new StringParameter(parameter.Name));
            }
            else if (paramType == typeof(bool))
            {
                result.Add(new BooleanParameter(parameter.Name));
            }
            // TODO: Add more types as needed
        }
        return result;

        static bool IsParameterProperty(PropertyInfo property)
        {
            // TODO: Add more types as needed
            return
                property.GetSetMethod()?.IsPublic is true &&
                property.GetGetMethod()?.IsPublic is true &&
                (
                    property.PropertyType == typeof(string) || property.PropertyType == typeof(bool)
                );
        }
    }
}
```

and for referencing the template:

```cs
public abstract class TemplateParametersProviderBase : ITemplateParametersProvider
{
    public TemplateParameters ToTemplateParameters()
    {
        var result = new TemplateParameters();
        foreach (var parameter in GetType().GetProperties()
            .Where(IsParameterProperty))
        {
            result[parameter.Name] = parameter.GetValue(this);
        }
        return result;

        static bool IsParameterProperty(PropertyInfo property)
        {
            return
                property.GetSetMethod()?.IsPublic is true &&
                property.GetGetMethod()?.IsPublic is true;
        }
    }
}
```

then we could just work with POJO's and not even have to have source-generators

**Comment by premun** [comment]
Oh, I see, that seems like it would be very easy and still get us there. I like this a lot.

I wonder if we can also get the default values this way.
I also wonder if we'd need to specify both `<TTemplate, TParameters>` or if just `TTemplate` would be enough.

**Comment by Meir017** [comment]
> Oh, I see, that seems like it would be very easy and still get us there. I like this a lot.
> 
> I wonder if we can also get the default values this way. I also wonder if we'd need to specify both `<TTemplate, TParameters>` or if just `TTemplate` would be enough.

I think the POJO class can specify a default value properties we could extract, then only if the passed value to the template is different we will emit that parameter

**Comment by premun** [comment]
I think we should implement this one the next. @Meir017 is this something you'd be interested in or should I go for it?

**Comment by Meir017** [comment]
@premun let me extract the relevant source-generator code from #355 and let's see what's missing

**Comment by premun** [comment]
@Meir017 but do we need the source-generator? Maybe we can just have the POCO parameters and the generic template references as a first step? Is my understanding correct that the source-generators are theoretically orthogonal to supporting the POCOs?

Or do I misunderstand how you plan to make it work?

**Comment by Meir017** [comment]
> @Meir017 but do we need the source-generator? Maybe we can just have the POCO parameters and the generic template references as a first step? Is my understanding correct that the source-generators are theoretically orthogonal to supporting the POCOs?
> 
> Or do I misunderstand how you plan to make it work?

The source-generator is required in order for the template's definition to be able to reference the parameters through the `parameters` property

**Comment by Meir017** [comment]
I think that a current approach could be to use the `*Library` classes, then effectively replaces azure's pipelines templating with embedding the actual template into the pipeline. then parameters could be passed to the custom Library's constructor and nothing complex will be required.

The downside of this approach is that it's not compatable with existing azure pipelines templates

**Comment by premun** [comment]
So the only benefit of the source generator is that I can then do `parameters.BuildType` instead of `parameters["BuildType"]`?

I am asking all this because adding a source generator is a big deal for maintenance and just all around support.
Adding it means we really need to make it work flawless because if someone uses the library and it will start breaking their builds with very hard to find code (usually for people), they will just stop using the library.

Secondly, I am unsure about whether the generators would be a dedicated packages from nuget people would reference or we'd just include it right away and let people turn it on via making their definition partial + adding the attribute.

**Comment by Meir017** [comment]
> So the only benefit of the source generator is that I can then do `parameters.BuildType` instead of `parameters["BuildType"]`?

yes.

> I am asking all this because adding a source generator is a big deal for maintenance and just all around support. Adding it means we really need to make it work flawless because if someone uses the library and it will start breaking their builds with very hard to find code (usually for people), they will just stop using the library.

users will need to explicitly use the source-generator by adding an attribute to their template definition

> Secondly, I am unsure about whether the generators would be a dedicated packages from nuget people would reference or we'd just include it right away and let people turn it on via making their definition partial + adding the attribute.

Hmm, I'm not sure about this, the package `OneOf` we use has a dedicated package `OneOf.SourceGenerator`
